- hosts: macbook
  tasks:
    - name: install homebrew packages
      homebrew:
        name:
          [
            "bash",
            "boost",
            "clang-format",
            "cmake",
            "coreutils",
            "dive",
            "dos2unix",
            "glib",
            "go",
            "htop",
            "iperf3",
            "mage",
            "mtr",
            "neovim",
            "ninja",
            "nmap",
            "p7zip",
            "packer",
            "pbzip2",
            "pigz",
            "pixz",
            "pkg-config",
            "python",
            "python@2",
            "rsync",
            "ssh-copy-id",
            "swiftformat",
            "swiftlint",
            "tcptraceroute",
            "the_silver_searcher",
            "tmux",
            "vault",
            "vim",
            "weechat",
            "wget",
            "xxhash",
            "xz",
            "youtube-dl",
            "zsh",
            "zsh-syntax-highlighting",
          ]
        state: present
    - name: install homebrew casks
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - brave-browser
        - burp-suite
        - docker
        - firefox
        - google-chrome
        - iterm2
        - keepassxc
        - kindle
        - macpass
        - postman
        - powershell
        - slack
        - spotify
        - sublime-text
        - vagrant
        - virtualbox
        - virtualbox-extension-pack
        - visual-studio-code
        - zoomus
