---
- hosts: macbook
  tasks:
  - name: install homebrew packages
    homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - autoconf
      - awscli
      - bash
      - boost
      - clang-format
      - cmake
      - coreutils
      - doxygen
      - exploitdb
      - fping
      - go
      - hashcat
      - htop
      - iperf3
      - libdvdcss
      - mutt
      - nasm
      - ninja
      - nmap
      - p7zip
      - pbzip2
      - pigz
      - pxz
      - python3
      - s3cmd
      - ssh-copy-id
      - the_silver_searcher
      - tmux
      - unix2dos
      - vim
      - w3m
      - wget
      - youtube-dl
      - zsh
      - zsh-syntax-highlighting
  - name: tap homebrew repos
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - caskroom/cask
  - name: install homebrew casks
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - amazon-music
      - docker
      - handbrake
      - hipchat
      - iterm2
      - macpass
      - skype-for-business
      - vagrant
      - virtualbox
      - visual-studio-code
      - vmware-horizon-client
      - wireshark
